import {
  Utensils,
  Car,
  Home,
  Gamepad2,
  HeartPulse,
  GraduationCap,
  ShoppingBag,
  Repeat,
  Ellipsis,
  Tag,
  Plane,
  Briefcase,
  Wallet,
  Gift,
  Coffee,
  Dumbbell,
  Wifi,
  Smartphone,
  BookOpen,
  Music,
  Pill,
  PawPrint,
  Fuel,
  Wrench,
  CreditCard,
  PiggyBank,
  Landmark,
  Building2,
  Shirt,
  Film,
  Baby,
  Umbrella,
  Bus,
  Bike,
  type LucideIcon
} from 'lucide-react'

const CATEGORY_ICONS: Record<string, LucideIcon> = {
  utensils: Utensils,
  car: Car,
  home: Home,
  'gamepad-2': Gamepad2,
  'heart-pulse': HeartPulse,
  'graduation-cap': GraduationCap,
  'shopping-bag': ShoppingBag,
  repeat: Repeat,
  ellipsis: Ellipsis,
  tag: Tag,
  plane: Plane,
  briefcase: Briefcase,
  wallet: Wallet,
  gift: Gift,
  coffee: Coffee,
  dumbbell: Dumbbell,
  wifi: Wifi,
  smartphone: Smartphone,
  'book-open': BookOpen,
  music: Music,
  pill: Pill,
  'paw-print': PawPrint,
  fuel: Fuel,
  wrench: Wrench,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  landmark: Landmark,
  'building-2': Building2,
  shirt: Shirt,
  film: Film,
  baby: Baby,
  umbrella: Umbrella,
  bus: Bus,
  bike: Bike
}

export const CATEGORY_ICON_OPTIONS = Object.keys(CATEGORY_ICONS)

export function getCategoryIcon(icon: string): LucideIcon {
  return CATEGORY_ICONS[icon] ?? Tag
}
